# Generated by Django 4.2.1 on 2023-05-27 11:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import students.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_ID",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        choices=[
                            ("MTE", "Mechatronics"),
                            ("ECE", "Electronics and Communication"),
                            ("CSE", "Computer Science"),
                            ("MEC", "Mechanical"),
                            ("MAT", "Mathematics"),
                            ("EEE", "Electrical and Electronics"),
                            ("IUC", "Inter University Course"),
                            ("PHY", "Physics"),
                            ("CHM", "Chemistry"),
                            ("HUM", "Humanities"),
                            ("CRA", "Coursera"),
                            ("AER", "Aeronautical"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ENG", "Engineering"),
                            ("COM", "Commerce"),
                            ("ARC", "Architecture"),
                            ("PHR", "Pharmacy"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=50)),
                ("event_details", models.CharField(max_length=200)),
                ("event_time", models.DateTimeField()),
                ("event_venue", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester_number", models.IntegerField()),
                (
                    "gpa",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "credits",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("fees", models.IntegerField()),
                ("fees_paid", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=50, null=True)),
                (
                    "phone_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[students.models.phone_number_validator],
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "enrolment_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[students.models.number_validator],
                    ),
                ),
                (
                    "registration_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[students.models.number_validator],
                    ),
                ),
                (
                    "year_of_joining",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[students.models.year_validator],
                    ),
                ),
                (
                    "year_of_graduation",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[students.models.year_validator],
                    ),
                ),
                (
                    "current_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[students.models.year_validator],
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="students.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "student_ID",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="students.student",
                    ),
                ),
                ("permanent_address1", models.TextField(max_length=200)),
                ("permanent_address2", models.TextField(max_length=200)),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
                (
                    "pin_code",
                    models.IntegerField(validators=[students.models.pincode_validator]),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentDetails",
            fields=[
                (
                    "ward_ID",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="students.student",
                    ),
                ),
                ("father_name", models.CharField(max_length=50)),
                ("father_occupation", models.CharField(max_length=50)),
                ("father_email", models.EmailField(max_length=50)),
                (
                    "father_contact_no",
                    models.IntegerField(
                        validators=[students.models.phone_number_validator]
                    ),
                ),
                ("mother_name", models.CharField(max_length=50)),
                ("mother_occupation", models.CharField(max_length=50)),
                ("mother_email", models.EmailField(max_length=50)),
                (
                    "mother_contact_no",
                    models.IntegerField(
                        validators=[students.models.phone_number_validator]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "subjectID",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "credits",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "department_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentSubjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_point",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "agg_attendance",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("C", "Current"),
                            ("R", "Re-Registered"),
                            ("D", "Completed"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "semester_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.semester",
                    ),
                ),
                (
                    "studentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                (
                    "subjectID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sessions",
            fields=[
                ("attendance", models.BooleanField()),
                ("date", models.DateField()),
                ("session_ID", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("L", "Lecture"),
                            ("T", "Tutorial"),
                            ("P", "Practical"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.studentsubjects",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="semester",
            name="student",
            field=models.ForeignKey(
                default="a524bd15-8983-4ae6-ba5e-624cefc45522",
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
            ),
        ),
        migrations.CreateModel(
            name="Exams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("max_score", models.IntegerField()),
                (
                    "score",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("INT-1", "In-Semester Examination 1"),
                            ("INT-2", "In-Semester Examination 2"),
                            ("FISAC", "FISAC"),
                            ("MISAC", "MISAC"),
                            ("END", "End-Semester Examination"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Applications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("C", "Completed"),
                            ("P", "Processing"),
                            ("R", "Registered"),
                        ],
                        max_length=1,
                    ),
                ),
                ("file", models.JSONField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "ann_ID",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("ann_title", models.CharField(max_length=50)),
                ("ann_info", models.TextField(max_length=200)),
                (
                    "dept_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.department",
                    ),
                ),
            ],
        ),
    ]
