# Generated by Django 4.2.1 on 2023-06-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_semester_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(blank=True, upload_to="students/default.png"),
        ),
    ]
