# Generated by Django 4.2.1 on 2023-06-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_student_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(
                blank=True,
                default="students/default.png",
                null=True,
                upload_to="students/",
            ),
        ),
    ]
