# Generated by Django 4.2.1 on 2023-06-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registration_number",
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
    ]
